services:
  - type: web
    name: mangogramapp
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /src/*
        destination: /index.html
